MvcCityConst/MvcCityConst/Models/ContactType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCityConst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactType()
        {
            this.Contacts = new HashSet<Contacts>();
        }
    
        public int Nx { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacts> Contacts { get; set; }
    }
}

MvcCityConst/MvcCityConst/Models/Contacts.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCityConst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int Nx { get; set; }
        public System.Guid ID { get; set; }
        public int Profiles_Nx { get; set; }
        public int ContactType_Nx { get; set; }
        public string Value { get; set; }
        public int Priority { get; set; }
        public string Comments { get; set; }
        public int State { get; set; }
        public System.DateTime DI { get; set; }
        public Nullable<System.Guid> UI { get; set; }
        public Nullable<System.DateTime> DM { get; set; }
        public Nullable<System.Guid> UM { get; set; }
        public Nullable<System.Guid> Tokens_ID { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual Profiles Profiles { get; set; }
    }
}

MvcCityConst/MvcCityConst/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CC = MvcCityConst.Common;

namespace MvcCityConst.Controllers
{
    public class ContactsController : Controller
    {
        public ActionResult ContactsControl(int Profiles_Nx, bool IsReadOnly)
        {
            ViewBag.Profiles_Nx = Profiles_Nx;
            ViewBag.IsReadOnly = IsReadOnly;
            return PartialView();
        }

        public ActionResult gvContacts(int? Profiles_Nx, bool IsReadOnly = true)
        {
            if (Profiles_Nx != null)
            {
                var db = CC.CityConstDB;
                var Model = db.Contacts.Where(wh => wh.Profiles_Nx == Profiles_Nx.Value && wh.State != 0).Select(sel => new { sel.Nx, sel.ID, sel.Priority, sel.State, sel.ContactType_Nx, sel.ContactType.Name, sel.Value, sel.Comments }).OrderBy(ob => ob.Priority).ToList();
                Session["gvContacts"] = Model;
                Session["gvContacts_IsReadOnly"] = IsReadOnly;
            }
            ViewBag.IsReadOnly = (bool)Session["gvContacts_IsReadOnly"];
            return PartialView(Session["gvContacts"]);
        }
        public ActionResult EditContact(int Profiles_Nx, int? Nx = null, bool IsReadOnly = true)
        {
            var db = CC.CityConstDB;
            Models.Contacts Model = new Models.Contacts { Priority = 1 };
            if (Nx != null)
                Model = db.Contacts.Find(Nx.Value);
            ViewBag.Profile_Nx = Profiles_Nx;
            ViewBag.IsReadOnly = IsReadOnly;
            return PartialView(Model);
        }
        public ActionResult DeleteContact(int Contacts_Nx)
        {
            var db = CC.CityConstDB;
            var cnt = db.Contacts.Single(s => s.Nx == Contacts_Nx);
            cnt.State = 0;
            cnt.DM = DateTime.Now;
            cnt.UM = Account.GetCurrentUserID();
            db.SaveChanges();
            return new HttpStatusCodeResult(200);
        }
        public ActionResult cbContactType(string InputValueName, int? ContactTypeNx, bool IsReadOnly = false)
        {
            ViewBag.InputValueName = InputValueName;
            ViewBag.ContactTypeNx = ContactTypeNx;
            ViewBag.IsReadOnly = IsReadOnly;
            var db = CC.CityConstDB;
            var Model = db.ContactType.ToList();
            return PartialView(Model);
        }

        public ActionResult CheckPriorityContact(int Profiles_Nx)
        {
            return Content(CC.CityConstDB.Contacts.Any(any => any.Profiles_Nx == Profiles_Nx && any.State > 0 && any.Priority == 0) ? "OK" : "ERROR");
        }
        // { Profiles_Nx:'@ViewBag.Profile_Nx',Contact_Nx:$('#Contact_Nx').val() , Value: $('#Value').val(), ContactType_Nx: cbContactType.GetValue(), Priority: !!$('#Priority').attr('checked') }
        public ActionResult SaveContact(int Profiles_Nx, int? Contact_Nx, string Value, int ContactType_Nx, bool Priority, string Comments)
        {
            var db = CC.CityConstDB;
            Models.Contacts Contact;
            Models.Tokens Token = null;
            if (Priority)
                db.Contacts.Where(wh => wh.Profiles_Nx == Profiles_Nx).ToList().ForEach(cnt => db.Contacts.Single(s => s.Nx == cnt.Nx).Priority = 1);
            if (Contact_Nx == null || Contact_Nx == 0)
            {
                Contact = new Models.Contacts();
                Contact.Comments = Comments;
                Contact.ContactType_Nx = ContactType_Nx;
                Contact.ID = Guid.NewGuid();
                Contact.Profiles_Nx = Profiles_Nx;
                Contact.Priority = Priority ? 0 : 1;
                Contact.State = 3;
                Token = ConfirmationTokens.Issue("Подтверждение контакта", 12);
                Contact.Tokens_ID = Token.ID;

                Contact.DI = DateTime.Now;
                Contact.UI = Account.GetCurrentUserID();
                Contact.Value = Value;
                db.Contacts.Add(Contact);


            }
            else
            {
                Contact = db.Contacts.Single(s => s.Nx == Contact_Nx.Value);
                Contact.Comments = Comments;
                Contact.ContactType_Nx = ContactType_Nx;
                Contact.Priority = Priority ? 0 : 1;
                if (Contact.Value != Value)
                {
                    Contact.State = 3;
                    Token = ConfirmationTokens.Issue("Подтверждение контакта", 12);
                    Contact.Tokens_ID = Token.ID;
                }
                Contact.DM = DateTime.Now;
                Contact.UM = Account.GetCurrentUserID();
                Contact.Value = Value;
            }
            db.SaveChanges();
            if (ContactType_Nx == 1 && Token != null)
            {
                string href = string.Format("http://{0}/Account/Confirmation/{1}?Code={2}", HttpContext.Request.Url.Authority, Token.ID.ToString(), Token.Code.ToString());
                string Body = string.Format("Указанный Вами контакт будет разблокирован после подтверждения. Для подтверждения и активации контакта перейдите по <a href='{0}'>ссылке</a>", href);
                Messages.Mail.SendMail(Contact.Value, "Подтверждение контакта", Body);
                Messages.Mail.SendMessage(Account.ProfilesCache.Single(s=>s.ID== Account.SystemProfileID).Nx, 2, "Подтверждения контакта", "На указанный Вами контакт отправлено письмо с инструкциями по подтверждению контакта", new List<int> { Account.GetUserProfile_Nx(Account.GetCurrentUserID().Value).Value });
            }
            return new HttpStatusCodeResult(200);
        }

    }
}

MvcCityConst/MvcCityConst/Views/Contacts/ContactsControl.cshtml
@if (ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly)
{
<button type="button" class="btn btn-success" onclick='$.post("/Contacts/EditContact", {Profiles_Nx:"@ViewBag.Profiles_Nx", IsReadOnly:@Html.Raw(ViewBag.IsReadOnly ? "true" : "false")}, function(data) { data = "<div>" + data + "</div>"; $("body").append(data); })' style="margin-bottom:5px;">Новый контакт</button>
}
@Html.Action("gvContacts", new { Profile_Nx = ViewBag.Profile_Nx, IsReadOnly = ViewBag.IsReadOnly })
<div style="display:none" id="gvContactsContextMenu">
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation"><a href="#" onclick="EditContact('{KeyValue}');" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-pencil" style="margin-right:5px"></div>Редактировать</a></li>
        @if (!ViewBag.IsReadOnly)
        {
        <li role="presentation"><a href="#" onclick="DeleteContact('{KeyValue}');" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-remove" style="margin-right:5px"></div>Удалить</a></li>
        }
    </ul>
</div>
<script>
    function gvContactsShowOptions(s, e) {


        $(s).popover({ animation: true, placement: 'auto right', title: 'Действия', html: true, content: $('#gvContactsContextMenu').html().split('{KeyValue}').join(e) });
        $(s).popover('show');

        $('body').on('click', function (e) {
            $('.popover').each(function () {
                $(this).popover('destroy');
                $('body').off('click');
            });
        });

    }
    function EditContact(e) {
        e = parseInt(e);
        $.get("/Contacts/EditContact", {Profiles_Nx:"@ViewBag.Profiles_Nx",Nx:e, IsReadOnly:'@Html.Raw(ViewBag.IsReadOnly == true)'}, function(data) { data = "<div>" + data + "</div>"; $("body").append(data); })
    }
    function DeleteContact(e) {
        e = parseInt(e);

        if (confirm("Удалить контакт?")) {
            $.post('/Contacts/DeleteContact', { Contacts_Nx: e }, function (data) { gvContacts.PerformCallback({ Profiles_Nx: '@ViewBag.Profiles_Nx', IsReadOnly:'@Html.Raw(ViewBag.IsReadOnly == true)' }); });
        }
    }
</script>

MvcCityConst/MvcCityConst/Views/Contacts/EditContact.cshtml
@model MvcCityConst.Models.Contacts

<script>
    function CheckContactType(s, e) {
        if (cbContactType.GetValue())
            $('.cbContactType').parent().removeClass('has-error').addClass('has-success');
        else
            $('.cbContactType').parent().removeClass('has-success').addClass('has-error');
    }

    function CheckValue(fnk) {
        if ($('#Value').val().length > 0) {
            $.get("/Account/CheckEmail", { Email: $('#Value').val(),Contact_Nx:'@Model.Nx', ContactType_Nx: cbContactType.GetValue(), CheckWithPriority: !!$('#Priority').prop('checked')  }, function (data) {
                if (data == "OK") {
                    $('#Value').parent().removeClass('has-error').addClass('has-success');
                }
                else {
                    $('#Value').parent().removeClass('has-success').addClass('has-error');
                }
                if (fnk) fnk();
            });
        }
        else
            $('#Value').parent().removeClass('has-success').addClass('has-error');
    }
    function CheckPriority() {
        if (!$('#Priority').prop('checked')) {
            alert('Нельзя снять пометку-Использовать для уведомлений. Вместо этого, укажите другой контакт, как - Использовать для уведомлений и в этом контакте пометка пропадет сама.');
            $('#Priority').prop('checked', 'checked');
        }
        else {
            $('#Priority').prop('checked', 'checked');
        }

    }
   </script>
<div class="modal fade EditContact" id="EditContact" tabindex="-1" role="dialog" aria-labelledby="EditContactLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onclick="$('#EditContact').modal('hide');" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">@Html.Raw(Model.Nx!=0?"Изменить контакт":"Новый контакт")</h4>
            </div>

            <div class="modal-body">
              
                <div class="form-group">
                    <input type="hidden" id="Contact_Nx" name="Contact_Nx" value="@Model.Nx" />
                    <input type="hidden" id="cbContactTypeValue" name="cbContactTypeValue" value="@Model.ContactType_Nx" />
                    <label class="control-label cbContactType">Тип контакта</label>
                    <div class="form-control">
                        @Html.Action("cbContactType", "Contacts", new { InputValueName = "cbContactTypeValue", ContactTypeNx = Model.ContactType_Nx, IsReadOnly=ViewBag.IsReadOnly })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label Value">Значение</label>
                    <input type="text" class="form-control" id="Value" name="Value" value="@Model.Value" onblur="CheckValue();">
                </div>
                <label class="checkbox-inline">
                    <input type="checkbox" id="Priority" name="Priority" @Html.Raw(Model.Priority==0?"checked":"") onclick="CheckPriority();">Использовать для уведомлений
                </label>
                <div class="form-group">
                    <label class="control-label Comments">Комментарии</label>

                    <textarea id="ContactComments" class="form-control" rows="3" name="ContactComments">@Model.Comments</textarea>
                </div>
            </div>
            <div class="modal-footer">
                @if (ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly)
                {
                <button type="button" class="btn btn-success" onclick='SaveContact();'>Сохранить</button>
                }
                <button type="button" class="btn btn-default" onclick="$('#EditContact').modal('hide');">Закрыть</button>

            </div>
        </div>
    </div>
</div>
<script>
    (function () {
        $('#EditContact').modal('show');
        if ($('[data-backdrop="true"]').length > 1)
            $('#EditContact').attr('data-backdrop', 'false');
        $('#EditContact').on('hidden.bs.modal', function (e) {
            $('#EditContact').parent().remove();
        })
    })();
</script>
@if (ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly)
{
    <script>
        function Save() {
            if ($('.has-error').length == 0) {
                $.get("/Contacts/SaveContact", { Profiles_Nx: '@ViewBag.Profile_Nx', Contact_Nx: $('#Contact_Nx').val(), Value: $('#Value').val(), ContactType_Nx: cbContactType.GetValue(), Priority: !!$('#Priority').prop('checked'), Comments: $('#ContactComments').val() }, function (data) {
                    gvContacts.PerformCallback({ Profiles_Nx: '@ViewBag.Profile_Nx', IsReadOnly: '@Html.Raw(ViewBag.IsReadOnly == true)' });
                    $('#EditContact').modal('hide');
                });
            }
        }

        function SaveContact() {
            CheckContactType();
            CheckValue(function () {
                if (!$('#Priority').prop('checked')) {
                    $.get("/Contacts/CheckPriorityContact", { Profiles_Nx: '@ViewBag.Profile_Nx' }, function (data) {
                        debugger;
                        if (data == "ERROR") $('#Priority').prop('checked', 'checked');
                        Save();
                    });
                }
                else {
                    Save();
                }

            });
        }
        (function () { $('#EditContact input[type!=checkbox], textarea').removeAttr('disabled'); })();
    </script>
}
else
{
    <script>
        (function () { $('#EditContact input, textarea').attr('disabled', 'disabled'); })();
    </script>
}

MvcCityConst/MvcCityConst/Views/Contacts/cbContactType.cshtml
@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "cbContactType";

        settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        settings.Properties.ClientSideEvents.LostFocus = "CheckContactType";
        settings.Properties.ClientSideEvents.ValueChanged = string.Format("function(s,e){{ if('{0}'.length>0) $('#{0}').val(s.GetValue()); }}", ViewBag.InputValueName);
        settings.SelectedIndex = 0;
        settings.PreRender = (sender, e) =>
        {
            if (ViewBag.ContactTypeNx != null && ViewBag.ContactTypeNx!=0)
            {
                MVCxComboBox cmb = sender as MVCxComboBox;
                cmb.Value = ViewBag.ContactTypeNx;
            }
        };
        settings.CallbackRouteValues = new { Controller = "Contacts", Action = "cbContactType", InputValueName= ViewBag.InputValueName, ContactTypeNx= ViewBag.ContactTypeNx };
        settings.ControlStyle.Border.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        settings.Properties.ButtonStyle.Border.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        settings.Properties.DropDownStyle = DropDownStyle.DropDownList;
        settings.Properties.TextField = "Name";
        settings.Properties.ValueField = "Nx";
        settings.Properties.ValueType = typeof(int);
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.ClientEnabled = ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly;
        //settings.Properties.FilterMinLength = 2;
        //settings.Properties.CallbackPageSize = 15;
        settings.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Always;
    }
                ).BindList(Model).GetHtml()

MvcCityConst/MvcCityConst/Views/Contacts/gvContacts.cshtml
@*sel.Nx,sel.ID, sel.Priority, sel.State, sel.ContactType.Name, sel.Value, sel.Comments*@


@{
    var grid = Html.DevExpress().GridView(settings =>
    {

        settings.Name = "gvContacts";
        settings.CallbackRouteValues = new { Controller = "Contacts", Action = "gvContacts" };
        settings.CustomActionRouteValues = new { Controller = "Contacts", Action = "gvContacts" };
        //settings.ClientSideEvents.EndCallback = "function(s,e) {$('#SelectedInMsg').val().split(';').forEach(function(val, idx, obj) { var chk = '#chk' + val;$(chk).attr('checked', 'checked'); });}";
        settings.KeyFieldName = "Nx";
        settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        settings.SettingsPager.Visible = true;
        //settings.SettingsPager.Mode = GridViewPagerMode.ShowAllRecords;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.HideDataCells;
        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = true;
        //settings.Settings.VerticalScrollBarMode = ScrollBarMode.Visible;
        // settings.ClientSideEvents.BeginCallback = "gvEmployees_OnBeginCallback";
        settings.Settings.ShowGroupPanel = true;
        settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        //settings.ClientSideEvents.RowDblClick = string.Format("function(s,e){{debugger; var id=s.GetRowKey(e.visibleIndex);/* alert(id);*/ $.get('{0}',{{ID:id}},function(data){{ data='<div class=\"ViewMessage\">'+data+'</div>'; $('body').append(data);}});}}", Url.Action("ViewMessage", "Messages"));
        settings.HtmlRowPrepared = (sender, e) =>
        {
            if (e.RowType != GridViewRowType.Data) return;
            if ((int)e.GetValue("State") != 1)
                e.Row.ForeColor = System.Drawing.Color.Gray;

        };
        settings.Columns.Add(column =>
        {
            column.SetDataItemTemplateContent(c =>
            {
                // ViewContext.Writer.Write(c.Grid.GetRowValues(c.VisibleIndex, "FactVolume") != null?"":string.Format("<table style='width:100%'><tr><td align='center'><span id='spEditResource' title='Редактировать ресурс' style='cursor:pointer;' class=\"glyphicon glyphicon-pencil\" onclick=\"EditRecource({0},{1},'{2}','{3}','{4}');\"></span></td><td align='center'><span id='DeleteResource' title='Удалить ресурс' style='cursor:pointer;' class=\"glyphicon glyphicon-remove\" onclick=\"DeleteResource({0});\"></span></td></tr></table>", c.KeyValue,c.Grid.GetRowValues(c.VisibleIndex, "IDСпРесурсы"), ((DateTime)c.Grid.GetRowValues(c.VisibleIndex, "ДатаВыполнения")).ToShortDateString(), c.Grid.GetRowValues(c.VisibleIndex, "ОбъемПодр"), c.Grid.GetRowValues(c.VisibleIndex, "КомментарийПодр")));
                ViewContext.Writer.Write(string.Format("<table style='width:100%'><tr><td align='center'><span id='ShowOptions_{0}' title='Действия' style='cursor:pointer;' class='glyphicon glyphicon-option-vertical' onclick=\"event.stopPropagation();gvContactsShowOptions(this,{0});\"></span></td></tr></table>", c.KeyValue));
            });
            column.Width = System.Web.UI.WebControls.Unit.Pixel(30);

        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Тип контакта";
            column.FieldName = "Name";
            column.ColumnType = MVCxGridViewColumnType.Default;
           column.Width = System.Web.UI.WebControls.Unit.Pixel(90);
            // column.AdaptivePriority = 1;
        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Значение";
            column.FieldName = "Value";
            //column.Width = System.Web.UI.WebControls.Unit.Pixel(150);
        });
        settings.Columns.Add(column =>
        {

            column.Caption = "Для уведомлений";
            column.AdaptivePriority = 1;
            column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
            column.Width = System.Web.UI.WebControls.Unit.Pixel(90);
            column.SetDataItemTemplateContent(c =>
            {
                ViewContext.Writer.Write((int)c.Grid.GetRowValues(c.VisibleIndex, "ContactType_Nx") != 1 ? "" : string.Format("<input type='checkbox' {0} disabled />", (int)c.Grid.GetRowValues(c.VisibleIndex, "Priority") == 0 ? "checked" : ""));
            });

        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Комментарии";
            column.FieldName = "Comments";

        });




    });
}

@grid.Bind(Model).GetHtml()