MvcCityConst/MvcCityConst/Models/Jobs.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCityConst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobs()
        {
            this.Jobs1 = new HashSet<Jobs>();
            this.JobsAppointed = new HashSet<JobsAppointed>();
        }
    
        public int Nx { get; set; }
        public Nullable<int> Parent_Nx { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public System.DateTime DI { get; set; }
        public Nullable<System.Guid> UI { get; set; }
        public Nullable<System.DateTime> DM { get; set; }
        public Nullable<System.Guid> UM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobs> Jobs1 { get; set; }
        public virtual Jobs Jobs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobsAppointed> JobsAppointed { get; set; }
    }
}

MvcCityConst/MvcCityConst/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CC = MvcCityConst.Common;

namespace MvcCityConst.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        // GET: Jobs
        public ActionResult Index()
        {
           // var ds = CC.CityConstModel;
           //// bool IsUserBinded = ds.СпСотрСпРаботы.Any(any => any.СпСотрудники.SysUser == User.Identity.Name && any.СпСотрудники.State == 1);
           // int? EmplID = null;
            
           //     EmplID = ds.СпСотрСпРаботы.First(f => f.СпСотрудники.SysUser == User.Identity.Name && f.СпСотрудники.State == 1).IDСпСотрудники;
           // ViewBag.Contragent = ds.СпКонтрагенты.First(f => f.IDКонтрагенты == CC.ContrID);
           // ViewBag.EmplID = EmplID;

            var db = CC.CityConstDB;
            var CurUsr = Account.GetCurrentUserID();
            bool IsUserBinded = db.JobsToEmployees.Any(any => any.Employees.Profiles.Users_ID == CurUsr && any.Employees.State > 0 && any.State > 0);
            int? Nx = null;
            if (IsUserBinded)
                Nx = Account.ProfilesCache.Single(s => s.Nx == Account.GetUserProfile_Nx(Account.GetCurrentUserID().Value)).Employees.FirstOrDefault().Nx;
           
            ViewBag.Org= Account.ProfilesCache.FirstOrDefault(fod => fod.Employees.Any(s => s.State > 0 && s.Profiles.Users_ID == CurUsr)).Employees.Single().Organizations;
            ViewBag.Nx = Nx;
            return View();

        }
        public ActionResult BindToEmployee(int? Nx, string SelectedJobs, int FormType)
        {
                    if (!string.IsNullOrEmpty(SelectedJobs))
                    {
                        SelectedJobs = SelectedJobs.TrimStart('/');
                       // var ds = CC.CityConstModel;
                var db = CC.CityConstDB;
                if(Nx!=null)
                Nx = db.Profiles.Single(s => s.Nx == Nx.Value).Employees.First().Nx;
                var User_ID = Account.GetCurrentUserID();
                        SelectedJobs.Split('/').ToList().ForEach(item =>
                        {
                            int i = int.Parse(item);
                            switch (FormType)
                            {
                                case 0:
                                case 1:

                                    if ( !db.JobsToEmployees.Any(any=>any.State >0 && any.JobsAppointed_Nx==i && any.Employees_Nx==Nx) /*!ds.СпСотрСпРаботы.Any(any => any.IDРаботы == i && any.IDСпСотрудники == IDСотрудники)*/)
                                    {
                                        if (FormType == 1)
                                            db.JobsToEmployees.Where(wh => wh.JobsAppointed_Nx == i).ToList().ForEach(fe => { fe.State = 0; fe.DM = DateTime.Now; fe.UM = User_ID; });
                                        // ds.СпСотрСпРаботы.RemoveRange(ds.СпСотрСпРаботы.Where(wh => wh.IDРаботы == i));
                                        //ds.СпСотрСпРаботы.Add(new Models.СпСотрСпРаботы { IDСпСотрудники = IDСотрудники, IDРаботы = i });
                                        db.JobsToEmployees.Add(new Models.JobsToEmployees {  Employees_Nx=Nx.Value, JobsAppointed_Nx=i, DI=DateTime.Now, UI= User_ID, State=1 });
                                    }
                                    break;
                                case 2:
                                    //ds.СпСотрСпРаботы.RemoveRange(ds.СпСотрСпРаботы.Where(wh => wh.IDРаботы == i && wh.IDСпСотрудники== IDСотрудники.Value));
                                    db.JobsToEmployees.Where(wh => wh.JobsAppointed_Nx == i && wh.Employees_Nx == Nx.Value).ToList().ForEach(fe => { fe.State = 0; fe.DM = DateTime.Now; fe.UM = User_ID; });
                                    break;
                                case 3:
                                    //ds.СпСотрСпРаботы.RemoveRange(ds.СпСотрСпРаботы.Where(wh => wh.IDРаботы == i));
                                    db.JobsToEmployees.Where(wh => wh.JobsAppointed_Nx == i).ToList().ForEach(fe => { fe.State = 0; fe.DM = DateTime.Now; fe.UM = User_ID; });
                                    break;
                            }
                        });
                        db.SaveChanges();
            }
            
           
            return new HttpStatusCodeResult(200);
        }
       // gvJobs", new { Profiles_Nx = ViewBag.Org.Profiles_Nx, Nx= ViewBag.Nx })
        public ActionResult gvJobs(int? Profiles_Nx , int? Nx)
        {
            var ds = CC.CityConstModel;
          // int? ID = CC.ContrID.Value;
            var db = CC.CityConstDB;
            bool IsInRole = User.IsInRole("Client.Admin") || User.IsInRole("Sys.Admin");
            if (Session["gvJobs"] == null || Profiles_Nx != null)
            {
                var Model = db.JobsAppointed.Where(wh =>wh.State>0 && wh.Organizations.Profiles_Nx == Profiles_Nx &&(IsInRole || Nx == null || wh.JobsToEmployees.Any(any => any.Employees_Nx == Nx))).Select(sel => new
                {
                    sel.Nx,
                    JobsName = sel.Jobs.Name,
                    IsBinded = sel.JobsToEmployees.Count(),
                    BindetToEmpl = sel.JobsToEmployees.Where(wh=>wh.State>0).Select(s => s.Employees.Profile_Nx),
                    ManagedObjectLocationName = sel.ManagedObjectLocation.Name,
                    sel.PlanedDateBeg,
                    sel.PlanedDateEnd,
                    sel.Comments,
                    sel.DeclaredDateBeg,
                    sel.DeclaredDateEnd,
                    ResourceDeclared = db.JobsExecutedDeclared.Where(wh =>wh.State>0 && wh.JobsAppointedWithResources.JobsAppointed.Nx== sel.Nx).Count(), // ds.РаботаФактПодрядчик.Where(wh => wh.РаботаРесурсОбъем.Работы.IDРаботы == sel.IDРаботы).Count(),
                    ResourceApproved = db.JobsExecutedDeclared.Where(wh => wh.State > 0 && wh.JobsAppointedWithResources.JobsAppointed.Nx == sel.Nx && wh.VolumeConfirmed != null).Count() // ds.РаботаФактПодрядчик.Where(wh => wh.РаботаРесурсОбъем.Работы.IDРаботы == sel.IDРаботы && wh.РаботаФакт != null).Count()
                }).OrderBy(ob => ob.JobsName).ToList().Select(sel => new
                {
                    BindetToEmpl = sel.BindetToEmpl.Count() > 0 ? sel.BindetToEmpl.Select(s => Account.GetAuthority(s)).Aggregate((x, y) => x + ";" + y) : "не распределена",
                    sel.Nx,
                    sel.IsBinded,
                    sel.ResourceApproved,
                    sel.ResourceDeclared,
                    sel.JobsName,
                    sel.PlanedDateBeg,
                    sel.PlanedDateEnd,
                    sel.Comments,
                    sel.ManagedObjectLocationName,
                    sel.DeclaredDateBeg,
                    sel.DeclaredDateEnd
                }).ToList();
                Session["gvJobs"] = Model;
            }
            ViewBag.FullJobList = Nx == null || IsInRole;
            ViewBag.Profiles_Nx = Profiles_Nx;
            return View(Session["gvJobs"]);
        }
    }
}

MvcCityConst/MvcCityConst/Views/Jobs/BindToEmployee.cshtml
<style>
    BindToEmployee.input {
        max-width: none;
    }
</style>
<div class="modal fade BindToEmployee" id="BindToEmployee" tabindex="-1" role="dialog" aria-labelledby="BindToEmployeeLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="BindToEmployeeLabel">Выбрать сорудника</h4>
            </div>
            <div class="modal-body">

                @using (Html.BeginForm("BindToEmployee", "Jobs", FormMethod.Post))
                {
                    <input type="hidden" name="Nx" id="Nx" />
                    <input type="hidden" id="SelectedJobs" name="SelectedJobs" />
                    <input type="hidden" id="FormType" name="FormType" value="0" />
                    <div class="form-group">
                        <label>Сотрудник</label>
                        <div class="form-control" id="empl">
                            @*@Html.Partial("cbEmployee")*@

                            @*cbEmployees(bool Update = false, int? Organizations_Nx=null, bool IsWithAll = false, string cbEmployees_LostFocus = "", int? ViewID = null)*@
                            @Html.Action("cbEmployees", "Employees", new { Organizations_Nx= ViewBag.Org.Profiles_Nx, IsUseProfile = true })
                        </div>
                    </div>
                    <div class="form-group BindToEmployeeCheck">

                        <label>Заменить уже имеющих привязку сотрудников на указанного сотрудника</label><br />
                        @*<div class="form-control" id="empl">*@
                            <input type="checkbox" onchange="CheckChanged(this);" />
                        @* </div> *@
                    </div>
                }
                    </div>
            <div class="modal-footer">
                <button type="button" id="BindFormSubmit" class="btn btn-primary" onclick="debugger; if (BindEmplVaildate()) { if (typeof (cbEmployees.GetValue()) === 'number') $('.BindToEmployee #Nx').val(cbEmployees.GetValue()); if ($('#SelectedJobs').val().length > 0) $('.BindToEmployee form').submit(); else alert('Не выбрано ни одной работы!'); } ">Назначить</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('.BindToEmployee form').submit(function () {

                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        Update_gvJobs();
                    }
                });

            return false;
        });

    });
    function CheckChanged(obj) {
        debugger;
        if ($('#FormType').val() == 0 || $('#FormType').val() == 1)
        {
            if ($(obj).is(':checked'))
                $('#FormType').val(1);
            else
                $('#FormType').val(0);
        }
        else
            if ($('#FormType').val() == 2 || $('#FormType').val() == 3)
            {
                if ($(obj).is(':checked'))
                {
                    $('#FormType').val(3);
                    cbEmployees.SetEnabled(false);
                }
                else {
                    $('#FormType').val(2);
                    cbEmployees.SetEnabled(true);
                }
            }
    }
    function BindToEmployee_Clear() {
        if (cbEmployees) cbEmployees.SetText('');
        $('#Nx').val('');
        $('.errormess').remove();
        $('.BindToEmployee input[type=checkbox]').removeAttr('checked');
    }

    function ShowBindForm(FormType) {
        debugger;
        if (typeof(FormType)!=='undefined') {
            BindToEmployee_Clear();
            cbEmployees.SetEnabled(true);
            $('.BindToEmployeeCheck').attr('checked', '');
            if ($('#SelectedJobs').val().length > 0)
                $('#BindToEmployee').modal('show');
            else { alert('Не выбрано ни одной работы!'); return;}
            switch (FormType) {
                case 0:
                    $('#BindToEmployeeLabel').text('Назначить соруднику');
                    $('#FormType').val(0);
                    $('.BindToEmployeeCheck label').text('Заменить уже имеющих привязку сотрудников на указанного сотрудника');
                    $('#BindFormSubmit').text('Назначить');
                    break;
                case 2:
                    $('#BindToEmployeeLabel').text('Отвязать сорудника');
                    $('#FormType').val(2);
                    $('.BindToEmployeeCheck label').text('Удалить привязки всех назначенных сотрудников');
                    $('#BindFormSubmit').text('Отвязать');
                    break;

            }
        }
    }
    function Update_gvJobs() {
        $('#BindToEmployee').modal('hide');
        ClearSelection();
        gvJobs.PerformCallback({ Profiles_Nx: @ViewBag.Org.Profiles_Nx });

        /*<td align='center'><span id='spEmloerBinding' title='Привязка к сотруднику' style='cursor:pointer;' class=\"glyphicon glyphicon-transfer\" onclick=\"EmployeeBinding({0});\"></span></td><td align='center'><span id='ViewResources' title='Ресурсы' style='cursor:pointer;' class=\"glyphicon glyphicon-list-alt\" onclick=\"Resources({0});\"></span></td>*/
    }
    function BindEmplVaildate() {
        ret = true;
        if (cbEmployees && $('#Nx').val().length == 0 && cbEmployees.GetValue() == null && cbEmployees.GetEnabled()) {
            $('#empl').parent().removeClass('has-success').addClass('has-error');
           // $('.errormess.empl').remove();
           // $('#empl').after('<div class="errormess empl" style="color:red;">неверное значение</div>');
            ret = false;
        }
        else {
            // $('.errormess.empl').remove();
            $('#empl').parent().removeClass('has-error').addClass('has-success');
        }
        return ret;
    }
</script>

MvcCityConst/MvcCityConst/Views/Jobs/Index.cshtml
@{
    ViewBag.Title = "Работы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function ClearSelection() {
        $('#SelectedJobs').val('');
        $('input[id ^= "chk"]').removeAttr('checked');
    };
    function ChangeSelection(id){
        id='/'+id;
        var sj = $('#SelectedJobs').val();
        if (sj.indexOf(id) >= 0)
            sj = sj.split(id).join('');
        else
            sj += id;
        $('#SelectedJobs').val(sj);
    }
    //function RefreshCheckBoxes(s,e) {
    //    $('#SelectedJobs').val().split('//').forEach(function (val, idx, obj) {
    //        var chk = '#chk' + val;
    //        $(chk).attr('checked', 'checked');
    //    });
    //}
</script>
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6">
            @Html.Partial("ContragentInfo", (MvcCityConst.Models.Organizations)ViewBag.Org)
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Работы</h3>
    </div>
    <div class="panel-body">
        @if (ViewBag.Nx == null ||  User.IsInRole("Client.Admin") || User.IsInRole("Sys.Admin"))
        {
        <button type="button" class="btn btn-primary" onclick="ShowBindForm(0);">Назначить сотруднику</button>
        <button type="button" class="btn btn-primary" onclick="ShowBindForm(2);">Отвязать от сотрудника</button>
        @*<button type="button" class="btn btn-primary" onclick="BindToEmployee_Clear(); if ($('#SelectedJobs').val().length > 0) $('#BindToEmployee').modal('show'); else alert('Не выбрано ни одной работы!');">Назначить сотруднику</button>*@

        <div style="height:5px"></div>
        }
        @Html.Action("gvJobs", new { Profiles_Nx = ViewBag.Org.Profiles_Nx, Nx= ViewBag.Nx })
        

    </div>
</div>
@Html.Partial("BindToEmployee")

<script>
    (function(){
        var id =@ViewBag.Org.Profiles_Nx ;
        $('#ContragentID').val(id);
    })();
</script>

MvcCityConst/MvcCityConst/Views/Jobs/gvJobs.cshtml
@{ 
    var grid = Html.DevExpress().GridView(settings => {


        settings.Name = "gvJobs";
        settings.CallbackRouteValues = new { Controller = "Jobs", Action = "gvJobs" };
        settings.CustomActionRouteValues = new { Controller = "Jobs", Action = "gvJobs" };
        settings.ClientSideEvents.EndCallback = "function(s,e) {$('#SelectedJobs').val().split('/').forEach(function(val, idx, obj) { var chk = '#chk' + val;$(chk).attr('checked', 'checked'); });}";
        settings.KeyFieldName = "Nx";
        settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        settings.SettingsPager.Visible = true;
        //settings.SettingsPager.Mode = GridViewPagerMode.ShowAllRecords;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.HideDataCells;


        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = true;


        //settings.Settings.VerticalScrollBarMode = ScrollBarMode.Visible;
        // settings.ClientSideEvents.BeginCallback = "gvEmployees_OnBeginCallback";
        settings.SettingsPager.PageSize = 15;
        settings.Settings.ShowGroupPanel = true;
        settings.Settings.ShowFilterRow = true;
        settings.Settings.ShowFilterBar = GridViewStatusBarMode.Visible;
        settings.Settings.ShowFilterRowMenu = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.HtmlRowPrepared = (sender, e) =>
        {
            if (e.RowType != GridViewRowType.Data) return;
            if (e.GetValue("BindetToEmpl").ToString() != "не распределена")
                e.Row.BackColor = System.Drawing.Color.LightGreen;
        };

        settings.Columns.Add(column => {
            // column.Caption = "Действия";
            column.SetDataItemTemplateContent(c =>
            {
                ViewContext.Writer.Write(string.Format("<table style='width:100%'><tr><td align='center'><input type='checkbox' id='chk{0}' onclick='ChangeSelection({0});'/> </td></tr></table>", c.KeyValue));
            });
            column.Width = System.Web.UI.WebControls.Unit.Pixel(70);
            column.Visible = !(ViewBag.FullJobList != null && !(bool)ViewBag.FullJobList);
        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Работа";
            column.FieldName = "JobsName";

        });
        settings.Columns.Add(column =>
        {
            column.Caption = "ОбуМестоПоложение";
            column.FieldName = "ManagedObjectLocationName";

        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Распределена";
            column.FieldName = "BindetToEmpl";
            column.Visible = !(ViewBag.FullJobList != null && !(bool)ViewBag.FullJobList);
        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Ресурсы заявленные<br/>(подтвержденные)";
            column.SetDataItemTemplateContent(c =>
            {
                ViewContext.Writer.Write(string.Format("<button type='button' class='btn btn-primary btn-xs' onclick='window.location.href=\"{2}\"'>Редактировать {0} ({1})</button>", c.Grid.GetRowValues(c.VisibleIndex, "ResourceDeclared"), c.Grid.GetRowValues(c.VisibleIndex, "ResourceApproved"),Url.Action("Index", "Resources",new {Profiles_Nx=ViewBag.Profiles_Nx, Nx=c.KeyValue }) ));
            });
            column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Дата начала<br />(Заказчик)";
            column.FieldName = "PlanedDateBeg";
            column.ColumnType = MVCxGridViewColumnType.DateEdit;
            column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
            column.PropertiesEdit.DisplayFormatString = "dd.MM.yyyy";
            column.AdaptivePriority = 1;
        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Дата окнчания<br />(Заказчик)";
            column.FieldName = "PlanedDateEnd";
            column.ColumnType = MVCxGridViewColumnType.DateEdit;
            column.PropertiesEdit.DisplayFormatString = "dd.MM.yyyy";
            column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
            column.AdaptivePriority = 1;
        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Дата начала<br />(Подрядчик)";
            column.FieldName = "DeclaredDateBeg";
            column.ColumnType = MVCxGridViewColumnType.DateEdit;
            column.PropertiesEdit.DisplayFormatString = "dd.MM.yyyy";
            column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
            column.AdaptivePriority = 1;
            column.Visible = !(ViewBag.FullJobList != null && !(bool)ViewBag.FullJobList);
        });
        settings.Columns.Add(column =>
        {
            column.Caption = "Дата окнчания<br />(Подрядчик)";
            column.FieldName = "DeclaredDateEnd";
            column.ColumnType = MVCxGridViewColumnType.DateEdit;
            column.PropertiesEdit.DisplayFormatString = "dd.MM.yyyy";
            column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
            column.AdaptivePriority = 1;
            column.Visible = !(ViewBag.FullJobList != null && !(bool)ViewBag.FullJobList);
        });

        settings.Columns.Add(column =>
        {
            column.Caption = "Комментарии";
            column.FieldName = "Comments";
            column.AdaptivePriority = 1;
        });
    });
}

    @grid.Bind(Model).GetHtml()