MvcCityConst/MvcCityConst/Models/Departments.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCityConst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departments()
        {
            this.Employees = new HashSet<Employees>();
            this.Departments1 = new HashSet<Departments>();
        }
    
        public int Nx { get; set; }
        public string Name { get; set; }
        public int Organizations_Nx { get; set; }
        public Nullable<int> Employees_Nx { get; set; }
        public Nullable<int> ParentDepartment_Nx { get; set; }
        public string Comments { get; set; }
        public int State { get; set; }
        public System.DateTime DI { get; set; }
        public Nullable<System.Guid> UI { get; set; }
        public Nullable<System.DateTime> DM { get; set; }
        public Nullable<System.Guid> UM { get; set; }
        public string CompaundName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departments> Departments1 { get; set; }
        public virtual Departments Departments2 { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}

MvcCityConst/MvcCityConst/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CC = MvcCityConst.Common;
namespace MvcCityConst.Controllers
{
    public class DepartmentsController : Controller
    {
        // GET: Departments
        public ActionResult DepartmentsControl(int Profiles_Nx, bool IsReadOnly)
        {
            ViewBag.Profiles_Nx = Profiles_Nx;
            ViewBag.IsReadOnly = IsReadOnly;
            return PartialView();
        }
        public ActionResult tlDepartments(int? Profiles_Nx, bool IsReadOnly = true)
        {
            if (Profiles_Nx != null)
            {
                var db = CC.CityConstDB;
                var Model = db.Departments.Where(wh => wh.Organizations.Profiles_Nx == Profiles_Nx.Value && wh.State != 0).Select(sel => new { sel.Nx, sel.Name, sel.ParentDepartment_Nx, ParentDepartmenName = sel.Departments2.Name, sel.Comments }).OrderBy(ob => ob.ParentDepartmenName).ThenBy(tb => tb.Name).ToList();
                Session["tlDepartments"] = Model;
                Session["tlDepartments_IsReadOnly"] = IsReadOnly;
            }
            ViewBag.IsReadOnly = (bool)Session["tlDepartments_IsReadOnly"];
            return PartialView(Session["tlDepartments"]);
        }
        public ActionResult EditDepartment(int Profiles_Nx, int? Nx = null, bool IsReadOnly = true)
        {
            var db = CC.CityConstDB;
            Models.Departments Model = new Models.Departments();
            if (Nx != null)
                Model = db.Departments.Find(Nx.Value);
            ViewBag.Profile_Nx = Profiles_Nx;
            ViewBag.IsReadOnly = IsReadOnly;
            return PartialView(Model);
        }
        //CheckDepartmentName", { Profile_Nx: '@Model.Organizations.Profiles_Nx', DepartmentName: $('#DepartmentName').val(), Department_Nx: '@Model.Nx', ParentDepartment_Nx: cbDepartments.GetValue()

        public ActionResult CheckDepartmentName(int Profiles_Nx, string DepartmentName, int? Department_Nx, int? ParentDepartment_Nx)
        {
            var db = CC.CityConstDB;
            DepartmentName = CC.NormalizeName(DepartmentName);
            var rez = db.Departments.Where(any => any.State > 0 && any.Organizations.Profiles_Nx == Profiles_Nx && (ParentDepartment_Nx == null || any.ParentDepartment_Nx == ParentDepartment_Nx.Value) && (Department_Nx == null || any.Nx != Department_Nx.Value)).ToList().Any(any => CC.NormalizeName(any.Name) == DepartmentName) ? "ERROR" : "OK";
            return Content(rez);
        }

        public ActionResult cbDepartments(string InputValueName, int Profiles_Nx, int? Nx, bool IsReadOnly = false)
        {
            ViewBag.InputValueName = InputValueName;
            ViewBag.Departments_Nx = Nx;
            ViewBag.Profiles_Nx = Profiles_Nx;
            ViewBag.IsReadOnly = IsReadOnly;
            var db = CC.CityConstDB;
            var TempModel = db.Departments.Where(wh =>/*(Nx==null || wh.Nx!=Nx.Value) &&*/ wh.Organizations.Profiles_Nx == Profiles_Nx && wh.State > 0)/*.Select(sel=>new {sel.Nx, sel.Name, sel.Organizations_Nx, sel.ParentDepartment_Nx, sel.Departments2, CompaundName="" })*/.ToList();
            TempModel.ForEach(item =>
            {
                item.CompaundName = item.Name;
                var tmpitem = item;
                while (tmpitem.ParentDepartment_Nx != null)
                {
                    item.CompaundName= tmpitem.Departments2.Name + " => " + item.CompaundName;
                    tmpitem = tmpitem.Departments2;

                }
            });
            var Model = TempModel.OrderBy(ob => ob.Name).Select(sel=>new {sel.Nx,Name= sel.CompaundName }).ToList();
            ViewBag.Nx = Nx;
            return PartialView(Model);
        }

        public ActionResult CheckDepartments(int Department_Nx, int ParentDepartment_Nx)
        {
            var db = CC.CityConstDB;
            bool stop = false;
            bool success = true;
            var item = db.Departments.Find(Department_Nx);
            item.ParentDepartment_Nx = ParentDepartment_Nx;
            while (!stop)
            {
                if (item.ParentDepartment_Nx != null)
                {
                    if(item.ParentDepartment_Nx!= Department_Nx)
                        item = db.Departments.Find(item.ParentDepartment_Nx);
                    else
                    {
                        success = false;
                        stop = true;
                    }
                }
                else
                    stop = true;
            }
            return Content(success?"OK":"ERROR");
        }
        //SaveDepartment", { Profiles_Nx: '@ViewBag.Profile_Nx', Department_Nx: $('#Department_Nx').val(), DepartmentName: $('#DepartmentName').val(), ParentDepartment: cbDepartments.GetValue(),  Comments:
        public ActionResult SaveDepartment(int Profiles_Nx, int? Department_Nx, string DepartmentName, int? ParentDepartment_Nx, string Comments)
        {
            var db = CC.CityConstDB;
            Models.Departments dpt;
            if (Department_Nx == null || Department_Nx==0)
            {
                dpt = new Models.Departments { Comments = Comments, ParentDepartment_Nx = ParentDepartment_Nx, Name = DepartmentName, State = 1, DI = DateTime.Now, UI = Account.GetCurrentUserID(), Organizations=db.Organizations.First(f=>f.Profiles_Nx==Profiles_Nx) };
                db.Departments.Add(dpt);
            }
            else
            {
                dpt = db.Departments.Find(Department_Nx.Value);
                dpt.Name = DepartmentName;
                dpt.ParentDepartment_Nx = ParentDepartment_Nx;
                dpt.Comments = Comments;
                dpt.DM = DateTime.Now;
                dpt.UM = Account.GetCurrentUserID();
            }
            db.SaveChanges();
            return new HttpStatusCodeResult(200);
        }

        public ActionResult DeleteDepartment(int Nx)
        {
            var db = CC.CityConstDB;
            var item = db.Departments.Find(Nx);
            item.State = 0;
            item.DM = DateTime.Now;
            item.UM = Account.GetCurrentUserID();
            db.SaveChanges();
            return new HttpStatusCodeResult(200);
        }
    }

}

MvcCityConst/MvcCityConst/Views/Departments/DepartmentsControl.cshtml
@if (ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly)
{
    <button type="button" class="btn btn-success" onclick='$.post("/Departments/EditDepartment", {Profiles_Nx:"@ViewBag.Profiles_Nx", IsReadOnly:@Html.Raw(ViewBag.IsReadOnly ? "true" : "false")}, function(data) { data = "<div>" + data + "</div>"; $("body").append(data); })' style="margin-bottom:5px;">Новое подразделение</button>
}
@Html.Action("tlDepartments", new { Profile_Nx = ViewBag.Profile_Nx, IsReadOnly = ViewBag.IsReadOnly })

<div style="display:none" id="tlDepartmentsContextMenu">
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation"><a href="#" onclick="EditDepartment('{KeyValue}');" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-pencil" style="margin-right:5px"></div>Редактировать</a></li>
        @if (!ViewBag.IsReadOnly)
        {
            <li role="presentation"><a href="#" onclick="DeleteDepartment('{KeyValue}');" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-remove" style="margin-right:5px"></div>Удалить</a></li>
        }
    </ul>
</div>
<script>
    function tlDepartmentsShowOptions(s, e) {


        $(s).popover({ animation: true, placement: 'auto left', title: 'Действия', html: true, content: $('#tlDepartmentsContextMenu').html().split('{KeyValue}').join(e) });
        $(s).popover('show');

        $('body').on('click', function (e) {
            $('.popover').each(function () {
                $(this).popover('destroy');
                $('body').off('click');
            });
        });

    }
    function EditDepartment(e) {
        e = parseInt(e);
        $.get("/Departments/EditDepartment", { Profiles_Nx: "@ViewBag.Profiles_Nx", Nx: e, IsReadOnly: '@Html.Raw(ViewBag.IsReadOnly == true)' }, function (data) { data = "<div>" + data + "</div>"; $("body").append(data); });
    }
    function DeleteDepartment(e) {
        e = parseInt(e);

        if (confirm("Удалить подразделение?")) {
            $.post('/Departments/DeleteDepartment', { Nx: e }, function (data) { tlDepartments.PerformCallback({ Profiles_Nx: '@ViewBag.Profiles_Nx', IsReadOnly: '@Html.Raw(ViewBag.IsReadOnly == true)' }); });
        }
    }
</script>

MvcCityConst/MvcCityConst/Views/Departments/EditDepartment.cshtml
@model MvcCityConst.Models.Departments
<script>
    function CheckDepartmentName(fnk) {
        if ($('#DepartmentName').val().length > 0) {
            $.get("/Departments/CheckDepartmentName", { Profiles_Nx: '@ViewBag.Profile_Nx', DepartmentName: $('#DepartmentName').val(), Department_Nx: '@Model.Nx', ParentDepartment_Nx: cbDepartments.GetValue() }, function (data) {
                if (data == "OK") {
                    $('#DepartmentName').parent().removeClass('has-error').addClass('has-success');
                }
                else {
                    $('#DepartmentName').parent().removeClass('has-success').addClass('has-error');
                }
                if (fnk) fnk();
            });
        }
        else
            $('#DepartmentName').parent().removeClass('has-success').addClass('has-error');
    }
</script>

<div class="modal fade EditDepartment" id="EditDepartment" tabindex="-1" role="dialog" aria-labelledby="EditDepartmentLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onclick="$('#EditDepartment').modal('hide');" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">@Html.Raw(Model.Nx != 0 ? "Изменить подразделение" : "Новое подразделение")</h4>
            </div>

            <div class="modal-body">

                <div class="form-group">
                    <input type="hidden" id="Department_Nx" name="Department_Nx" value="@Model.Nx" />
                    <input type="hidden" id="cbDepartmentsVal" name="cbDepartmentsVal" value="@Model.ParentDepartment_Nx" />
                    <label class="control-label cbDepartments">Старшее подразделение</label>
                    <div class="form-control">
                        @Html.Action("cbDepartments", "Departments", new { InputValueName = "cbDepartmentsVal", Profiles_Nx = ViewBag.Profile_Nx, Nx = Model.ParentDepartment_Nx, IsReadOnly = ViewBag.IsReadOnly })
                    </div>
                </div>
               
                <div class="form-group">
                    <label class="control-label Value">Подразделение</label>
                    <input type="text" class="form-control" id="DepartmentName" name="DepartmentName" value="@Model.Name" onblur="CheckDepartmentName();">
                </div>

                <div class="form-group">
                    <label class="control-label Comments">Комментарии</label>

                    <textarea id="DepartmentComments" class="form-control" rows="3" name="DepartmentComments">@Model.Comments</textarea>
                </div>
            </div>
            <div class="modal-footer">
                @if (ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly)
                {
                    <button type="button" class="btn btn-success" onclick='CheckAndSaveDepartment();'>Сохранить</button>
                }
                <button type="button" class="btn btn-default" onclick="$('#EditDepartment').modal('hide');">Закрыть</button>

            </div>
        </div>
    </div>
</div>

<script>
    (function () {
        $('#EditDepartment').modal('show');
        $('#EditDepartment').on('hidden.bs.modal', function (e) {
            $('#EditDepartment').parent().remove();
        })
    })();
</script>
@if (ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly)
{
    <script>
        function SaveDepartment() {
            if ($('.has-error').length == 0) {
                $.get("/Departments/SaveDepartment", { Profiles_Nx: '@ViewBag.Profile_Nx', Department_Nx: $('#Department_Nx').val(), DepartmentName: $('#DepartmentName').val(), ParentDepartment_Nx: cbDepartments.GetValue(), Comments: $('#DepartmentComments').val() }, function (data) {
                    tlDepartments.PerformCallback({ Profiles_Nx: '@ViewBag.Profile_Nx', IsReadOnly: '@Html.Raw(ViewBag.IsReadOnly == true)' });
                    $('#EditDepartment').modal('hide');
                });
            }
        }

        function CheckAndSaveDepartment() {
            CheckDepartments(null,null,function () {
                CheckDepartmentName(function () {
                    SaveDepartment();

                });
            });
        }
        function CheckDepartments(s, e, fnk) {
            if (cbDepartments.GetValue() && $('#Department_Nx').val() && $('#Department_Nx').val()!=0) {
                $.get('/Departments/CheckDepartments', {
                    Department_Nx: $('#Department_Nx').val(), ParentDepartment_Nx: cbDepartments.GetValue()
                }, function (data) {
                        if(data=='OK')
                            $('#cbDepartmentsVal').parent().removeClass('has-error').addClass('has-success').removeAttr('title');
                        else
                            $('#cbDepartmentsVal').parent().removeClass('has-success').addClass('has-error').attr('title','Циклическая ссылка на самого себя');
                      
                        if (fnk)
                            fnk();
                    }
                );
            }
            else {
                $('#cbDepartmentsVal').parent().removeClass('has-error').addClass('has-success').removeAttr('title');
                if (fnk)
                    fnk();
            }
        }
        (function () { $('#EditDepartment input[type!=checkbox], textarea').removeAttr('disabled'); })();
    </script>
}
else
{
    <script>
        (function () { $('#EditDepartment input, textarea').attr('disabled', 'disabled'); })();
    </script>
}

MvcCityConst/MvcCityConst/Views/Departments/cbDepartments.cshtml
@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "cbDepartments";

        settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        settings.Properties.ClientSideEvents.LostFocus = ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly? "CheckDepartments":"";
        settings.Properties.ClientSideEvents.ValueChanged = string.Format("function(s,e){{ if('{0}'.length>0) $('#{0}').val(s.GetValue()); }}", ViewBag.InputValueName);
        settings.SelectedIndex = 0;
        settings.PreRender = (sender, e) =>
        {
            if (ViewBag.Nx != null && ViewBag.Nx != 0)
            {
                MVCxComboBox cmb = sender as MVCxComboBox;
                cmb.Value = ViewBag.Nx;
            }
            else
            {
                MVCxComboBox cmb = sender as MVCxComboBox;
                cmb.Value = null;
            }
        };
        settings.CallbackRouteValues = new { Controller = "Departments", Action = "cbDepartments", InputValueName = ViewBag.InputValueName, Profiles_Nx = ViewBag.Profiles_Nx };
        settings.ControlStyle.Border.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        settings.Properties.ButtonStyle.Border.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        settings.Properties.DropDownStyle = DropDownStyle.DropDownList;
        settings.Properties.TextField = "Name";
        settings.Properties.ValueField = "Nx";
        settings.Properties.ValueType = typeof(int);
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.ClientEnabled = ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly;
        //settings.Properties.FilterMinLength = 2;
        //settings.Properties.CallbackPageSize = 15;
        settings.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Always;
    }
                ).BindList(Model).GetHtml()

MvcCityConst/MvcCityConst/Views/Departments/tlDepartments.cshtml
@{
    var treeList = Html.DevExpress().TreeList(settings =>
    {
        settings.Name = "tlDepartments";
        settings.CallbackRouteValues = new { Controller = "Departments", Action = "tlDepartments" };
        settings.CustomActionRouteValues = new { Controller = "Departments", Action = "tlDepartments" };
        settings.AutoGenerateColumns = false;
        settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        settings.ParentFieldName = "ParentDepartment_Nx";
        settings.KeyFieldName = "Nx";
        settings.SettingsBehavior.ExpandCollapseAction = TreeListExpandCollapseAction.NodeDblClick;
        settings.Settings.ShowRoot = true;

        settings.Columns.Add(column =>
        {
            column.Caption = "Подразделение";
            column.FieldName = "Name";
            // column.ColumnType = MVCxGridViewColumnType.Default;
            //column.Width = System.Web.UI.WebControls.Unit.Pixel(90);
            // column.AdaptivePriority = 1;
        });
        //settings.Columns.Add(column =>
        //{
        //    column.Caption = "Старшее подразделение";
        //    column.FieldName = "ParentDepartmenName";
        //    //column.Width = System.Web.UI.WebControls.Unit.Pixel(150);
        //});

        settings.Columns.Add(column =>
        {
            column.Caption = "Комментарии";
            column.FieldName = "Comments";

        });

        settings.Columns.Add(column =>
        {
            column.SetDataCellTemplateContent(c =>
            {
                // ViewContext.Writer.Write(c.Grid.GetRowValues(c.VisibleIndex, "FactVolume") != null?"":string.Format("<table style='width:100%'><tr><td align='center'><span id='spEditResource' title='Редактировать ресурс' style='cursor:pointer;' class=\"glyphicon glyphicon-pencil\" onclick=\"EditRecource({0},{1},'{2}','{3}','{4}');\"></span></td><td align='center'><span id='DeleteResource' title='Удалить ресурс' style='cursor:pointer;' class=\"glyphicon glyphicon-remove\" onclick=\"DeleteResource({0});\"></span></td></tr></table>", c.KeyValue,c.Grid.GetRowValues(c.VisibleIndex, "IDСпРесурсы"), ((DateTime)c.Grid.GetRowValues(c.VisibleIndex, "ДатаВыполнения")).ToShortDateString(), c.Grid.GetRowValues(c.VisibleIndex, "ОбъемПодр"), c.Grid.GetRowValues(c.VisibleIndex, "КомментарийПодр")));
                ViewContext.Writer.Write(string.Format("<table style='width:100%'><tr><td align='center'><span id='ShowOptions_{0}' title='Действия' style='cursor:pointer;' class='glyphicon glyphicon-option-vertical' onclick=\"event.stopPropagation();tlDepartmentsShowOptions(this,{0});\"></span></td></tr></table>", c.NodeKey));
            });
            column.Width = System.Web.UI.WebControls.Unit.Pixel(30);

        });
        settings.SettingsPager.Visible = true;
        settings.SettingsBehavior.AutoExpandAllNodes = true;
        settings.SettingsBehavior.AllowFocusedNode = true;
        settings.SettingsBehavior.AllowSort = true;
        settings.SettingsSelection.Enabled = false;
    });
}
@treeList.Bind(Model).GetHtml()