MvcCityConst/MvcCityConst/Models/Organizations.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCityConst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organizations()
        {
            this.Employees = new HashSet<Employees>();
            this.Hostels = new HashSet<Hostels>();
            this.Organizations1 = new HashSet<Organizations>();
            this.Departments = new HashSet<Departments>();
            this.Positions = new HashSet<Positions>();
            this.Contracts = new HashSet<Contracts>();
            this.JobsAppointed = new HashSet<JobsAppointed>();
        }
    
        public int Nx { get; set; }
        public string Name { get; set; }
        public int BusinessLegalForms_Nx { get; set; }
        public Nullable<int> Profiles_Nx { get; set; }
        public string CodeOGRN { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> ParentOrg_Nx { get; set; }
        public int EmployeesMaxNumber { get; set; }
        public int OrgType_Nx { get; set; }
        public string Comments { get; set; }
        public int State { get; set; }
        public System.DateTime DI { get; set; }
        public Nullable<System.Guid> UI { get; set; }
        public Nullable<System.DateTime> DM { get; set; }
        public Nullable<System.Guid> UM { get; set; }
    
        public virtual BusinessLegalForms BusinessLegalForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hostels> Hostels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organizations> Organizations1 { get; set; }
        public virtual Organizations Organizations2 { get; set; }
        public virtual Profiles Profiles { get; set; }
        public virtual OrgType OrgType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departments> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Positions> Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobsAppointed> JobsAppointed { get; set; }
    }
}

MvcCityConst/MvcCityConst/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CC = MvcCityConst.Common;

namespace MvcCityConst.Controllers
{
    [Authorize]
    public class OrganizationsController : Controller
    {
        public ActionResult Index()
        {
            if (User.IsInRole("Sys.Admin"))
            {
                ViewBag.IsReadOnly = false;
                int ViewID = Math.Abs(DateTime.Now.GetHashCode());
                ViewBag.ViewID = ViewID;
             
                return View();
            }
            else if(User.IsInRole("Client.Admin"))
            {
                ViewBag.IsReadOnly = false;
                int ViewID = Math.Abs(DateTime.Now.GetHashCode());
                ViewBag.ViewID = ViewID;
                var User_ID = Account.GetCurrentUserID();
                ViewBag.Nx = Account.ProfilesCache.FirstOrDefault(fod => fod.Employees.Any(s => s.State > 0 && s.Profiles.Users_ID == User_ID)).Employees.Single().Organizations.Nx;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult OrganizationControl(int? ViewID = null, bool IsReadOnly = false, int? Nx=null)
        {
            ViewBag.IsReadOnly = false;
             ViewID = ViewID?? Math.Abs(DateTime.Now.GetHashCode());
            ViewBag.ViewID = ViewID;
            ViewBag.Nx = Nx;
            return PartialView();
        }
        [Authorize(Roles = "Sys.Admin,Client.Admin")]
        public ActionResult gvOrganizations(bool Update=false, bool IsReadOnly=false, int? ViewID = null)
        {
            var db = CC.CityConstDB;
           // ViewID = ViewID ?? Math.Abs(DateTime.Now.GetHashCode());
            ViewBag.ViewID = ViewID;
            if (Session["gvOrganizations"+ ViewID] == null || Update)
            {
                var Model = db.Organizations.Where(wh => wh.State > 0).Select(sel => new { sel.Nx, sel.Profiles_Nx, sel.EmployeesMaxNumber, sel.Name, BusinessLegalFormsName = sel.BusinessLegalForms.Name, sel.State, Chief_Profiles_Nx = (sel.Employees.Any(s => s.State > 0 && s.Chief == 1) ? (int?)sel.Employees.FirstOrDefault(s => s.State > 0 && s.Chief == 1).Profile_Nx : null), EmplNumber = sel.Employees.Where(wh => wh.State > 0).Count(), sel.Comments, sel.OrgType.TypeName, sel.OrgType_Nx, Adress = sel.Profiles.Adress }).ToList().
                    Select(sel => new { sel.Adress, sel.Chief_Profiles_Nx, Chief = sel.Chief_Profiles_Nx != null ? Account.GetAuthority(sel.Chief_Profiles_Nx.Value) : "", OrgName = sel.Profiles_Nx == null ? "(" + sel.Name + "), " + sel.BusinessLegalFormsName : Account.GetAuthority(sel.Profiles_Nx.Value), sel.Nx, sel.Profiles_Nx, sel.State, sel.Comments, sel.EmployeesMaxNumber, sel.OrgType_Nx, sel.TypeName, sel.EmplNumber }).OrderBy(ob => ob.OrgType_Nx).ThenBy(tb => tb.OrgName);
                Session["gvOrganizations" + ViewID] = Model;
            }
                ViewBag.IsReadOnly = IsReadOnly;
            return PartialView(Session["gvOrganizations" + ViewID]);
        }
        public ActionResult GetOrgState(int Nx)
        {
            var db = CC.CityConstDB;
            var Org = db.Organizations.Find(Nx);
            return Content(Org.State.ToString());
        }
        [Authorize(Roles = "Sys.Admin,Client.Admin")]
        public ActionResult OrganizationEdit(int? Nx, int? ParrentOrg_Nx,  bool IsReadOnly=false, int? ViewID=null)
        {
            var db = CC.CityConstDB;
            ViewID = ViewID ?? Math.Abs(DateTime.Now.GetHashCode());
            ViewBag.ViewID = ViewID;
            Models.Organizations Org;
            if (Nx != null)
            {
                Org = db.Organizations.Single(s => s.Nx == Nx);
                if (Org.Profiles == null)
                {
                    Org.Profiles = db.Profiles.Add(new Models.Profiles { DI = DateTime.Now, FirstName = Org.Name, ID = Guid.NewGuid(), ProfileType_Nx = 2, State = 1, UI = Account.GetCurrentUserID() });
                    db.SaveChanges();
                    Org = db.Organizations.Single(s => s.Nx == Nx);
                    Account.CheckSystemCache(true);
                }
            }
            else
            {
                Org = new Models.Organizations { Nx=0, ParentOrg_Nx= ParrentOrg_Nx };
            }
            ViewBag.IsReadOnly = IsReadOnly;
            return PartialView(Org);
        }
        public struct Org { public int Nx { get; set; } public string Name { get; set; } }
        [AllowAnonymous]
        public ActionResult cbOrganizations(bool Update=false, bool IsWithAll=false, string cbOrganizations_LostFocus="", int? ViewID=null, bool IsUseProfileNx= false, string InputValueName= "")
        {
            //ViewID = ViewID ?? Math.Abs(DateTime.Now.GetHashCode());
            if (Update)
                Session["cbOrganizations"+ ViewID.ToString()] = null;
            var db = CC.CityConstDB;
            var Model =(List<Org>)(Session["cbOrganizations" + ViewID.ToString()] ?? db.Organizations.Where(wh => (wh.State == 1 || wh.State==3) && (!IsUseProfileNx || wh.Profiles_Nx!=null)).OrderBy(ob=>ob.Name).ToList().Select(sel=>new Org{ Nx= !IsUseProfileNx?sel.Nx:sel.Profiles_Nx.Value, Name=sel.Name+", "+sel.BusinessLegalForms.Name }).ToList());
            if (User.IsInRole("Sys.Admin") && IsWithAll && Update)
                Model.Insert(0, new Org { Nx=0, Name="Все" });
            Session["cbOrganizations" + ViewID] = Model;
            ViewData["OrgLostFocusEvent"+ ViewID] = cbOrganizations_LostFocus;
            Session["cbOrganizations" + ViewID] = Model;
            ViewBag.ViewID = ViewID;
            ViewBag.Update = Update;
            ViewBag.IsWithAll = IsWithAll;
            ViewBag.cbOrganizations_LostFocus = cbOrganizations_LostFocus;
            ViewBag.IsUseProfileNx = IsUseProfileNx;
            ViewBag.InputValueName = InputValueName;
            return View(Model);
        }
        [AllowAnonymous]
        public ActionResult cbBusinessLegalForms(string InputValueName="", bool Update = false, int? BusinessLegalFormsNx=null, bool IsReadOnly=false, int? ViewID = null)
        {
           // ViewID = ViewID ?? Math.Abs(DateTime.Now.GetHashCode());
            if (Update)
                Session["cbBusinessLegalForms"+ ViewID] = null;
            var db = CC.CityConstDB;
            var Model = Session["cbBusinessLegalForms" + ViewID] ?? db.BusinessLegalForms.Select(sel => new { sel.Nx, sel.Name }).ToList();
            Session["cbBusinessLegalForms" + ViewID] = Model;
            ViewBag.InputValueName = InputValueName;
            ViewBag.BusinessLegalFormsNx = BusinessLegalFormsNx;
            ViewBag.IsReadOnly = IsReadOnly;
            ViewBag.ViewID = ViewID;
            return View(Model);
        }
        [AllowAnonymous]
        public ActionResult CheckOrgname(string OrgName)
        {
          var ret= Account.CheckOrgName(OrgName) ? "OK" : "ERROR";
           return Content(ret);
        }

        public ActionResult OrgProfile(Models.Organizations Org, bool IsReadOnly=true, string AfterSaveAction="", int? ViewID = null)
        {
            ViewID = ViewID ?? Math.Abs(DateTime.Now.GetHashCode());
            ViewBag.IsReadOnly = IsReadOnly;
            ViewBag.CallBackFunk = AfterSaveAction;
            ViewBag.ViewID = ViewID;
            return PartialView(Org);
        }

        public ActionResult SaveOrgProfile(int? Org_Profiles_Nx, int cbBusinessLegalFormsValue, string Name, string SecondName, string ThirdName,string INN, string Adress, string CodeOgrn,string RegDate, int EmployeesMaxNumber, string Comments, string Email)
        {
            string ret = "OK";
            DateTime? RDate = (DateTime?)(string.IsNullOrEmpty(RegDate) ? null :(DateTime?) DateTime.Parse(RegDate));
            var db = CC.CityConstDB;
            Models.Profiles profile;
            Models.Organizations org;
            if(Org_Profiles_Nx==null)
            {

                var Profile_Nx = Account.RegisterNewOrganization(Name, cbBusinessLegalFormsValue, Email);

                profile = Account.ProfilesCache.Single(s => s.Nx == Profile_Nx);
                org = profile.Organizations.Single();
                profile.FirstName = Name;
                profile.SecondName = SecondName;
                profile.ThirdName = ThirdName;
                profile.INN = INN;
                profile.Adress = Adress;

                org.CodeOGRN = CodeOgrn;
                org.RegDate = RDate;
                org.Comments = Comments;
            }
            else
            {
                profile = db.Profiles.Single(s => s.Nx == Org_Profiles_Nx.Value);
                org = profile.Organizations.Single();
                profile.FirstName = Name;
                profile.SecondName = SecondName;
                profile.ThirdName = ThirdName;
                profile.INN = INN;
                profile.Adress = Adress;
                profile.Comments = Comments;
                profile.UM = Account.GetCurrentUserID();
                profile.DM = DateTime.Now;

                org.Name = Name;
                org.BusinessLegalForms_Nx = cbBusinessLegalFormsValue;
                org.CodeOGRN = CodeOgrn;
                org.RegDate = RDate;
                org.Comments = Comments;
                org.UM = profile.UM;
                org.DM = DateTime.Now;
            }
            db.SaveChanges();
            Account.CheckSystemCache(true);
            return Content(ret);
        }
        //DeleteOrganization', { Nx: e 

        public ActionResult DeleteOrganization(int Nx, Guid? curusr=null, DateTime? dttm_n=null, bool ForceCheckSystemCache = true)
        {
           
            curusr = curusr ?? Account.GetCurrentUserID();
            dttm_n = dttm_n ?? DateTime.Now;
            var db = CC.CityConstDB;
            var Org = db.Organizations.Find(Nx);

MvcCityConst/MvcCityConst/Views/Organizations/Index.cshtml
@{

  //  Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Action("OrganizationControl", new {ViewID=ViewBag.ViewID, IsReadOnly= ViewBag.IsReadOnly, Nx= ViewBag.Nx })

MvcCityConst/MvcCityConst/Views/Organizations/OrganizationControl.cshtml
@if (ViewBag.Nx == null)
{
    ViewBag.Title = "Список организаций";
    if (!ViewBag.IsReadOnly)
    {
        <button type="button" class="btn btn-success" onclick="$.get('/Organizations/OrganizationEdit',{ViewID:'@ViewBag.ViewID'}, function (data) {  window['ShowOrgModal_@ViewBag.ViewID']('Добавить организацию', data); });">Добавить организацию</button>
    }
    <div style="height:5px"></div>
    @Html.Action("gvOrganizations", new { IsReadOnly = ViewBag.IsReadOnly, ViewID = ViewBag.ViewID })


    <div class="modal fade OrgModalAlert_uniq_@ViewBag.ViewID" id="OrgModalAlert_uniq_@ViewBag.ViewID" style="overflow-y: auto;" tabindex="-1" role="dialog" aria-labelledby="OrgModalAlert_uniq_Label_@ViewBag.ViewID">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" onclick="$('#OrgModalAlert_uniq_@ViewBag.ViewID').modal('hide');" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" onclick="window['gvOrganizations_@ViewBag.ViewID'].PerformCallback({Update:true, IsReadOnly:@Html.Raw(ViewBag.IsReadOnly == true).ToString().ToLower()});$('#OrgModalAlert_uniq_@ViewBag.ViewID').modal('hide');">Закрыть</button>
                </div>
            </div>
        </div>
    </div>


    <div style="display:none" id="gvOrganizationsContextMenu_@ViewBag.ViewID">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation"><a href="#" onclick="window['EditOrg_@ViewBag.ViewID']('{KeyValue}');" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-pencil" style="margin-right:5px"></div>Редактировать</a></li>
            @if (ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly)
            {
                <li role="presentation"><a href="#" onclick="window['DeleteOrg_@ViewBag.ViewID']('{KeyValue}');" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-remove" style="margin-right:5px"></div>Удалить</a></li>
                <li role="presentation"><a href="#" class="UnRestrictOrg_@ViewBag.ViewID" onclick="window['UnRestrictOrg_@ViewBag.ViewID']('{KeyValue}')" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-open" style="margin-right:5px"></div>Снять ограничения</a></li>
                <li role="presentation"><a href="#" class="UnBlockOrg_@ViewBag.ViewID" onclick="window['UnBlockOrg_@ViewBag.ViewID']('{KeyValue}')" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-envelope" style="margin-right:5px"></div>Разблокировать</a></li>
                <li role="presentation"><a href="#" class="BlockOrg_@ViewBag.ViewID" onclick="window['BlockOrg_@ViewBag.ViewID']('{KeyValue}')" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-lock" style="margin-right:5px"></div>Заблокировать</a></li>
                <li role="presentation"><a href="#" class="RestrictOrg_@ViewBag.ViewID" onclick="window['RestrictOrg_@ViewBag.ViewID']('{KeyValue}')" style="color:dimgrey; font-size:12px"><div class="glyphicon glyphicon-lock" style="margin-right:5px"></div>Ограничить</a></li>
            }
        </ul>
    </div>

    <script>
        window['ShowOrgModal_@ViewBag.ViewID']=function(Title, Body) {
            $('#OrgModalAlert_uniq_@ViewBag.ViewID .modal-title').children().remove();
            $('#OrgModalAlert_uniq_@ViewBag.ViewID .modal-title').append(Title);
            $('#OrgModalAlert_uniq_@ViewBag.ViewID .modal-body').children().remove();
            $('#OrgModalAlert_uniq_@ViewBag.ViewID .modal-body').append(Body);
            $('#OrgModalAlert_uniq_@ViewBag.ViewID').modal('show');
        };
        window['EditOrg_@ViewBag.ViewID']=function (e) {
            e = parseInt(e);
            $.get("/Organizations/OrganizationEdit", { Nx: e, IsReadOnly: '@Html.Raw(ViewBag.IsReadOnly)', ViewID: '@ViewBag.ViewID' }, function (data) { debugger; window['ShowOrgModal_@ViewBag.ViewID']('<span>Редактировать организацию</span>', '<div>' + data + '</div>'); });


        };

        window['DeleteOrg_@ViewBag.ViewID']=function (e) {
            e = parseInt(e);

            if (confirm("Удалить организацию, все ее контакты, всех сотрудников и все филиалы?")) {
                $.post('/Organizations/DeleteOrganization', { Nx: e }, function (data) { window['gvOrganizations_@ViewBag.ViewID'].PerformCallback({ Update: 'true', IsReadOnly: '@Html.Raw(ViewBag.IsReadOnly == true)',ViewID:'@ViewBag.ViewID' }); });
            }
        };

        window['UnRestrictOrg_@ViewBag.ViewID'] = function (Nx) {
            $.get('/Home/Comment', { Header: 'Причина снятия ограничений', SuccessAction: 'function(reason){ window["DoSmth_@ViewBag.ViewID"](reason,1,' + Nx + ');}' }, function (data) { data = '<div>' + data + '</div>'; $('body').append(data); });
        };
        window['UnBlockOrg_@ViewBag.ViewID'] = function (Nx) {
            $.get('/Home/Comment', { Header: 'Причина снятия блокировки', SuccessAction: 'function(reason){ window["DoSmth_@ViewBag.ViewID"](reason,2,' + Nx + ');}' }, function (data) { data = '<div>' + data + '</div>'; $('body').append(data); });
        };
        window['BlockOrg_@ViewBag.ViewID']=function(Nx) {
            $.get('/Home/Comment', { Header: 'Причина блокировки', SuccessAction: 'function(reason){ window["DoSmth_@ViewBag.ViewID"](reason,3,' + Nx + ');}' }, function (data) { data = '<div>' + data + '</div>'; $('body').append(data); });
        }
        window['RestrictOrg_@ViewBag.ViewID']=function (Nx) {
            $.get('/Home/Comment', { Header: 'Причина введения ограничений', SuccessAction: 'function(reason){ window["DoSmth_@ViewBag.ViewID"](reason,4,' + Nx + ');}' }, function (data) { data = '<div>' + data + '</div>'; $('body').append(data); });
        }

        window["DoSmth_@ViewBag.ViewID"]=function (reason, CmdType, Nx) {
            $.get('/Organizations/RestrictonActions', { Reason: reason, CmdType: CmdType, Nx: Nx }, function () { window['gvOrganizations_@ViewBag.ViewID'].PerformCallback({ Update: 'true', IsReadOnly: '@Html.Raw(ViewBag.IsReadOnly == true)',ViewID:'@ViewBag.ViewID' }); });
        }





        window['ShowgvOrganizationsOptions_@ViewBag.ViewID']=function (s, e) {
            $.get('/Organizations/GetOrgState', { Nx: e }, function (data) {
                debugger;
                var ContextMenu = $('#gvOrganizationsContextMenu_@ViewBag.ViewID').clone().attr('id', 'ContextMenu_@ViewBag.ViewID');

                if (parseInt(data) == 3) {
                    $('.ConfirmationRequest_@ViewBag.ViewID', ContextMenu).parent().remove();
                    $('.RestrictOrg_@ViewBag.ViewID', ContextMenu).parent().remove();
                }
                else
                    if (parseInt(data) == 2) {
                        $('.UnRestrictOrg_@ViewBag.ViewID', ContextMenu).parent().remove();
                        $('.BlockOrg_@ViewBag.ViewID', ContextMenu).parent().remove();
                        $('.RestrictOrg_@ViewBag.ViewID', ContextMenu).parent().remove();
                    }
                    else {
                        $('.UnRestrictOrg_@ViewBag.ViewID', ContextMenu).parent().remove();
                        $('.ConfirmationRequest_@ViewBag.ViewID', ContextMenu).parent().remove();
                    }
                $(s).popover({ animation: true, placement: 'auto right', title: 'Действия', html: true, content: $(ContextMenu).html().split('{KeyValue}').join(e) });
                $(s).popover('show');
            });



            $('body').on('click', function (e) {
                $('.popover').each(function () {
                    $(this).popover('destroy');
                    $('body').off('click');
                });
            });

        }
    </script>
}
else
{
    ViewBag.Title = "Профайл огранизации";
    @Html.Action("OrganizationEdit", "Organizations", new { Nx = ViewBag.Nx, IsReadOnly = ViewBag.IsReadOnly, ViewID = ViewBag.ViewID })
   
}

MvcCityConst/MvcCityConst/Views/Organizations/cbBusinessLegalForms.cshtml
@Html.DevExpress().ComboBox(
    settings =>
    {
        settings.Name = "cbBusinessLegalForms" +(ViewBag.ViewID != null ? "_" + ViewBag.ViewID.ToString() : "");

        settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        settings.Properties.ClientSideEvents.LostFocus = "CheckBusinessLegalForms" +(ViewBag.ViewID != null ? "_" + ViewBag.ViewID.ToString() : "");
        settings.Properties.ClientSideEvents.ValueChanged =string.Format("function(s,e){{ if('{0}'.length>0) $('#{0}').val(s.GetValue()); }}", ViewBag.InputValueName);
        settings.SelectedIndex = 0;
        settings.PreRender = (sender, e) =>
        {
            if (ViewBag.BusinessLegalFormsNx != null && ViewBag.BusinessLegalFormsNx !=0)
            {
                MVCxComboBox cmb = sender as MVCxComboBox;
                cmb.Value = ViewBag.BusinessLegalFormsNx;
            }
        };
        settings.ClientEnabled = ViewBag.IsReadOnly != null && !ViewBag.IsReadOnly;
        settings.CallbackRouteValues = new { Controller = "Organizations", Action = "cbBusinessLegalForms", ViewID = ViewBag.ViewID };
        settings.ControlStyle.Border.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        settings.Properties.ButtonStyle.Border.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        settings.Properties.DropDownStyle = DropDownStyle.DropDownList;
        settings.Properties.TextField = "Name";
        settings.Properties.ValueField = "Nx";
        settings.Properties.ValueType = typeof(int);
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        //settings.Properties.FilterMinLength = 2;
        //settings.Properties.CallbackPageSize = 15;
        settings.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Always;
    }
                ).BindList(Model).GetHtml()